// documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/provided/modules/angular/app.component.ts
import { NgStyle } from '@angular/common';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import type { OnInit } from '@angular/core';
import { Component, ViewChild } from '@angular/core';

import { AgGridAngular } from 'ag-grid-angular';
import type { ColDef } from 'ag-grid-community';
import { ClientSideRowModelModule, CommunityFeaturesModule, ModuleRegistry } from 'ag-grid-community';

import './styles.css';

ModuleRegistry.registerModules([CommunityFeaturesModule, ClientSideRowModelModule]);

@Component({
    standalone: true,
    imports: [AgGridAngular, HttpClientModule, NgStyle],
    selector: 'my-app',
    template: `
        <div style="height: 100%; display: flex; flex-direction: column;">
            <div style="margin-bottom: 5px;">
                <button (click)="fillLarge()">Fill 100%</button>
                <button (click)="fillMedium()">Fill 60%</button>
                <button (click)="fillExact()">Exactly 400 x 400 pixels</button>
            </div>
            <div [ngStyle]="style">
                <ag-grid-angular
                    style="width: 100%; height:100%;"
                    #agGrid
                    [rowData]="rowData"
                    [columnDefs]="columnDefs"
                />
            </div>
        </div>
    `,
})
export class AppComponent implements OnInit {
    @ViewChild('agGrid') agGrid!: AgGridAngular<IOlympicData>;

    public style: any = {
        width: '100%',
        height: '100%',
        flex: '1 1 auto',
    };

    public columnDefs: ColDef[] = [
        { field: 'athlete', width: 150 },
        { field: 'age', width: 90 },
        { field: 'country', width: 150 },
        { field: 'year', width: 90 },
        { field: 'date', width: 150 },
        { field: 'sport', width: 150 },
        { field: 'gold', width: 100 },
        { field: 'silver', width: 100 },
        { field: 'bronze', width: 100 },
        { field: 'total', width: 100 },
    ];
    public rowData!: IOlympicData[];

    constructor(private http: HttpClient) {}

    ngOnInit() {
        this.http
            .get<IOlympicData[]>('https://www.ag-grid.com/example-assets/olympic-winners.json')
            .subscribe((data) => {
                this.rowData = data;
            });
    }

    fillLarge() {
        this.setWidthAndHeight('100%', '100%');
    }

    fillMedium() {
        this.setWidthAndHeight('60%', '60%');
    }

    fillExact() {
        this.setWidthAndHeight('400px', '400px');
    }

    setWidthAndHeight(width: string, height: string) {
        this.style = {
            width: width,
            height: height,
        };
    }
}

// testing/module-size/src/App.tsx
import { useMemo, useRef, useState } from 'react';

import {
    ColDef,
    ModuleRegistry,
    themeQuartz
} from 'ag-grid-community';

import {
    /** __PLACEHOLDER__START__ */  /** __PLACEHOLDER__END__ */
} from 'ag-grid-community';
import {
    /** __ENTERPRISE_PLACEHOLDER__START__ */ IntegratedChartsModule /** __ENTERPRISE_PLACEHOLDER__END__ */
} from 'ag-grid-enterprise';
import { AgGridReact } from 'ag-grid-react';

ModuleRegistry.registerModules([
    /** __PLACEHOLDER__START__ */  /** __PLACEHOLDER__END__ */
]);

ModuleRegistry.registerModules([
    /** __ENTERPRISE_PLACEHOLDER__START__ */ IntegratedChartsModule /** __ENTERPRISE_PLACEHOLDER__END__ */,
]);

export const App = () => {
    const gridRef = useRef<AgGridReact>(null);
    const containerStyle = useMemo(() => ({ width: '100%', height: '100%' }), []);
    const gridStyle = useMemo(() => ({ height: '100%', width: '100%' }), []);
    const [rowData, setRowData] = useState<any[]>();
    const [columnDefs] = useState<ColDef[]>([
        {
            field: 'athlete',
            minWidth: 150,
        },
        { field: 'age', maxWidth: 90 },
        { field: 'country', minWidth: 150 },
        { field: 'year', maxWidth: 90 },
        { field: 'date', minWidth: 150 },
        { field: 'sport', minWidth: 150 },
        { field: 'gold' },
        { field: 'silver' },
        { field: 'bronze' },
        { field: 'total' },
    ]);
    const defaultColDef = useMemo<ColDef>(() => {
        return {
            flex: 1,
            minWidth: 100,
            filter: true,
        };
    }, []);

    const onGridReady = () => {
        fetch('https://www.ag-grid.com/example-assets/olympic-winners.json')
            .then((resp) => resp.json())
            .then((data) => setRowData(data));
    };

    return (
        <div style={containerStyle}>
            <div className="example-wrapper">
                <div style={gridStyle} className={'ag-theme-quartz-dark'}>
                    <AgGridReact
                        ref={gridRef}
                        theme={themeQuartz}
                        rowData={rowData}
                        columnDefs={columnDefs}
                        defaultColDef={defaultColDef}
                        onGridReady={onGridReady}
                    />
                </div>
            </div>
        </div>
    );
};
